# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/User/Desktop/CTI/AN II/SEM 2/ac/lab2/lab2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/User/Desktop/CTI/AN II/SEM 2/ac/lab2/lab2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/User/Desktop/CTI/AN II/SEM 2/ac/lab2/lab2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/User/Desktop/CTI/AN II/SEM 2/ac/lab2/lab2.srcs/sources_1/new/SSD.vhd}
  {C:/Users/User/Desktop/CTI/AN II/SEM 2/ac/lab2/lab2.srcs/sources_1/new/MPG.vhd}
  {C:/Users/User/Desktop/CTI/AN II/SEM 2/ac/lab2/lab2.srcs/sources_1/new/lab2.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/User/Desktop/CTI/AN II/SEM 2/ac/lab2/lab2.srcs/constrs_1/new/const.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/User/Desktop/CTI/AN II/SEM 2/ac/lab2/lab2.srcs/constrs_1/new/const.xdc}}]


synth_design -top lab2 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab2.dcp

catch { report_utilization -file lab2_utilization_synth.rpt -pb lab2_utilization_synth.pb }
